# Custom Language File for Launcher Customizer

[ejs.app]
title = "묘쿤 런처"

[ejs.landing]
mediaGitHubURL = "https://github.com/BabyBear7/myokun"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@myokun0314"
mediaChzzkURL = "https://chzzk.naver.com/live/67794ee9a42903e72f71a90ee01064cc"
mediaDiscordURL = "https://discord.gg/tu9Ca9nBDx"

[ejs.settings]
sourceGithubLink = "https://github.com/BabyBear7/myokun"
supportLink = "https://github.com/BabyBear7/myokun/issues"

[ejs.welcome]
welcomeHeader = "대장 전용 런처!"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
